### ISSUE TITLE
Is it possible to use vue-i18n with the library?

### ISSUE THREAD

**Issue by vprodus** [Valian/live_vue#17]
`const i18n = createI18n({`
`  locale: 'ja',`
`  fallbackLocale: 'en',`
`  messages: {`
`    en: {`
`      message: {`
`        hello: 'hello world'`
`      }`
`    },`
`    ja: {`
`      message: {`
`        hello: 'こんにちは、世界'`
`      }`
`    }`
`  }`
`})`

`const initializeApp = context => {`
`  // initializeVueApp is a default function creating and initializing LiveVue App`
`  const app = initializeVueApp(context)`
`  // you can initialize additional plugins here, eg. Pinia`
`  app.use(pinia)`
`  app.use(i18n)`
`  return app`
`}`

doesn't work for me

**Comment by Valian** [comment]
What does it mean doesn't work? Could you give more details?
