### ISSUE TITLE
SSR error - Cannot find module './vue/server.mjs'

### ISSUE THREAD

**Issue by Valian** [Valian/live_vue#2]
## Reproduction
Ensure you run `mix assets.build` before and there's a file in `priv/vue/server.mjs`. Then, set `ssr_module: LiveVue.SSR.NodeJS` in your config and try visiting a page with server-side rendered component.

## Explanation
It's related to the upstream package `nodejs` not supporting importing ESM modules. I've added support for it, waiting for maintainers to merge and release the new version. 

You can track PR here:
https://github.com/revelrylabs/elixir-nodejs/pull/84

## Workaround
Add in your mix.exs deps:

```elixir
{:nodejs, github: "Valian/elixir-nodejs", branch: "master", override: true}
```

**Comment by Valian** [comment]
Update - there was some activity in the nodejs repo. My PR was rebased and ready to be merged. Hopefully soon ❤️

**Comment by Valian** [comment]
It's done! Everything should be working smoothly with nodejs ~> 3.1 🎉

**Comment by vheathen** [comment]
Could you please update dependency version? It still points to the ~> 2.0.

**Comment by Valian** [comment]
@vheathen 0.3.9 has been published with corrected dependency ❤️

**Comment by vheathen** [comment]
@Valian thanks a lot!
