### ISSUE TITLE
Question on live navigation 

### ISSUE THREAD

**Issue by Maxino22** [Valian/live_vue#26]
Hey used livesvelte trying out livevue,  how do we handle live navigation  something similar  to  on livesvelte please guide

```
push_navigate

<a href="/your-liveview-path" data-phx-link="redirect" data-phx-link-state="push">Redirect</a>
```

**Comment by Valian** [comment]
Hi @Maxino22, it's a good question. 

LiveView `<.link>` component simply renders `<a>` tag with bunch of data-attributes so they could be handled by phoenix client lib. What you presented here should work.

If you want to have a `<link>` component in the Vue world, I have a good news - recently I've created one for my own needs. Usage should be almost the same as with an elixir version:

```vue
<script setup lang="ts">
// save as link.vue or similar (in my case it's UiLink.vue)
import { computed } from 'vue'

interface Props {
  navigate?: string
  patch?: string
  href?: string
  replace?: boolean
  method?: string
  csrfToken?: boolean | string
}

const props = withDefaults(defineProps<Props>(), {
  replace: false,
  method: 'get',
  csrfToken: true,
})

const linkHref = computed(() => props.navigate || props.patch || props.href || '#')
</script>

<template>
  <a
    :href="linkHref"
    :data-method="method !== 'get' ? method : undefined"
    :data-csrf="method !== 'get' ? csrfToken : undefined"
    :data-to="method !== 'get' ? linkHref : undefined"
    :data-phx-link="navigate ? 'redirect' : patch ? 'patch' : undefined"
    :data-phx-link-state="(navigate || patch) && replace ? 'replace' : 'push'"
    v-bind="$attrs"
  >
    <slot></slot>
  </a>
</template>

```

usage 

```
<link patch="/my/path" :replace="true">
<link navigate="/live_view">
```

## Question

and here comes my question: Do you think it should be a part of LiveVue? Maybe just initial scaffolding could create that component? 🤔

**Comment by Maxino22** [comment]
this approach seems to work well come to think routing in vue and svelte is a bit different. Personally, I feel there is no harm in defining my own component
