### ISSUE TITLE
Code splitting support?

### ISSUE THREAD

**Issue by yasoob** [Valian/live_vue#30]
Hi!

I wonder if you have tackled or thought about code-splitting yet. It is kinda important to have some sort of code-splitting support. I want to use a vue component only on one page and don't want to bundle everything together in one App.js file.

In an ideal world, only the specific page that makes use of vue will have a link to the vue-related bundle.

**Comment by Valian** [comment]
Hi @yasoob! In the README it's called "lazy loading" and it's supported: 

https://github.com/Valian/live_vue?tab=readme-ov-file#lazy-loading-vue-components

```
import component1 from "./Component1.vue"
import component2 from "./Component2.vue"
const entryComponents = {
    Component1: component1,
    Component2: component2,
    Component3Lazy: () => import("./Component3.vue"),
}

// in app.js
const hooks = getHooks(entryComponents)
```

in the above example, `Component3` won't be a part of app.js bundle, but rather a separate file. You can of course use `() => import(...)` inside Vue component, it should be put into separate chunk as well. For more info, read [Vite documentation](https://vitejs.dev/guide/features#glob-import) 

In SSR, component should be rendered correctly and in addition it should include `<script src="..." preload>` tags to make hydration faster. 

Please let me know if you'll have any issues, but hopefully it will just work 🤗
