### ISSUE TITLE
Can't SSR any component with a slot

### ISSUE THREAD

**Issue by John-Goff** [Valian/live_vue#38]
It seems that the implementation of slots is not being handled correctly, any component with the most basic of slots is not rendering in SSR. 

Reproduction example: https://github.com/John-Goff/live_vue_ssr_issue, navigate to `/posts` to see the issue. 

This appears to be due to the slot content not being base64 encoded in SSR render for some reason, haven't tracked it down fully but adding `console.log(slots)` to the function returned from `getRender` in `assets/js/live_vue/server.ts` shows
```
{ default: 'Increase count' }
```

and shows the following error in server logs:
```
[error] Vue SSR error: InvalidCharacterError: The string to be decoded is not correctly encoded.                                      
    at atob (node:buffer:1296:13)                                                                                                     
    at file:///Users/johngoff/Repos/Hipo/assets/node_modules/live_vue/priv/static/server.js:29:40                                     
    at /Users/johngoff/Repos/Hipo/assets/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4407:31                                                                                                                                                                         at renderFnWithContext (/Users/johngoff/Repos/Hipo/assets/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:689:13)         
    at Module.renderSlot (/Users/johngoff/Repos/Hipo/assets/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2929:53)          
    at /Users/johngoff/Repos/Hipo/assets/vue/components/form-elements/hh-button.vue:39:5
    at renderFnWithContext (/Users/johngoff/Repos/Hipo/assets/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:689:13)
    at Module.renderSlot (/Users/johngoff/Repos/Hipo/assets/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2929:53)
    at /Users/johngoff/Repos/Hipo/assets/node_modules/vue-material-adapter/src/button/button.vue:16:37
    at Proxy.renderFnWithContext (/Users/johngoff/Repos/Hipo/assets/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:689:13)
```

I was able to fix this issue by making the following changes to my `assets/node_modules/live_vue/priv/static/server.js` file

```diff
--- deps/live_vue/priv/static/server.js 2024-11-13 12:32:53
+++ assets/node_modules/live_vue/priv/static/server.js  2024-11-13 14:52:44                                                            
@@ -19,11 +19,21 @@
         app: {},
     },
 };
+function getInnerHTML(base64) {
+  try {
+    const decoded = atob(base64).trim();
+    return decoded;
+  } catch {
+    return base64;
+  }
+}
 export const getRender = (componentsOrApp, manifest = {}) => {
     const { resolve, setup } = migrateToLiveVueApp(componentsOrApp);                                                                  
     return async (name, props, slots) => {
         const component = await resolve(name);
-        const slotComponents = mapValues(slots, base64 => () => h("div", { innerHTML: atob(base64).trim() }));                        
+        const slotComponents = mapValues(slots, base64 => () => {
+          return h("div", { innerHTML: getInnerHTML(base64) });
+        });
         const app = setup({
             createApp: createSSRApp,
             component,
```

I could make a PR if you like.

**Comment by Valian** [comment]
I double checked the implementation and it looks like when doing SSR slots are currently never base64-encoded. It shouldn't be needed, because we're not inserting them into HTML attribute as with `.vue` component. 

I'll fix and release fix in a moment. Thank you!

**Comment by Valian** [comment]
@John-Goff Version 0.5.5 has been released with a fix. Thank you for your report, personally I'm not using slots a lot and that's why it somehow slipped through! 😅 

Btw you might want to install `example_project` from this repository as a way of quickly testing changes to the live_vue package or trying out various things. If you'll run `mix assets.watch` in the live_vue root then all the JS changes will be reflected in realtime in the `example_project`

**Comment by John-Goff** [comment]
Thank you for the amazing quick fixes! I promise the next time I find an issue I'll take the time to make a proper PR about it 😄 I am a big fan of testing quick fixes directly in my node_modules or deps folder, it has the downsides of requiring you work on the outputted code but it has the upside of ensuring that the fix will actually fix my specific issue and not just the issue in the example. But I appreciate the effort and usefulness of a good example project, it certainly helped to browse the code to get started!
