### ISSUE TITLE
live-vue as PWA???

### ISSUE THREAD

**Issue by roger120981** [Valian/live_vue#6]
Is it posible to convert live-vue into a PWA like [liveview-svelte-pwa](https://github.com/tonydangblog/liveview-svelte-pwa) does or create a similar boilerplate?

**Comment by Valian** [comment]
Yes, I believe it should be possible 👍

On the other hand, I'm not sure if it's something that should be provided as a default, since there are multiple trade-offs involved and no one-fits-all solution. 

If someone would be willing to play with it, I'm more than happy to help 😉
